source 'https://rubygems.org'

gemspec

group :development do
  gem 'vagrant', git: 'https://github.com/mitchellh/vagrant.git', tag: 'v2.2.15'
  gem 'appraisal', '2.4.0'
  gem 'rubocop', '1.12.1', require: false
  gem 'coveralls', require: false
  gem 'rspec-its'
end

group :debug do
  gem 'byebug'
end
